version: "3.0"
services:  
  web:
    build: .
    ports:
      - "8009:80"
    volumes:
      - .:/app/
    links:
      - mongodb
    environment:
    - DB=mongodb://mongodb:27017/shostner
    command: poetry run uvicorn shostner.main:app --host 0.0.0.0 --port 80 --reload

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: shostner
      MONODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./mongodbdata:/data/db
